theme: jekyll-theme-minimal

title: [Welcome to Design and Analysis of Operating Systems]
description: [This site layouts all of the resources for the course and helps you get everything setup for the semester.]

show_downloads: ["true"]
