theme: jekyll-theme-minimal

title: [Design and Analysis of Operating Systems]
description: [Examines software comprising computing systems as it builds upon hardware to provide a programming environment. Looks at structure and function of editors, compilers/assemblers, linkers, etc.]

show_downloads: ["true"]
